### ISSUE TITLE
Follow up on https://stackoverflow.com/questions/65647375

### ISSUE THREAD

**Issue by fmbenhassine** [ptahchiev/hibernate-nlp#1]
Hi @ptahchiev ,

I just wanted to follow up on https://stackoverflow.com/questions/65647375. I was able to reproduce the issue with the same exception. However, I got other exceptions in different runs. Here are a couple of them:

```
...
2021-02-02 10:19:24.029 ERROR 42749 --- [search-export-1] ication$$EnhancerBySpringCGLIB$$b62662a6 : processing product: 11979 with name: Stim
2021-02-02 10:19:24.326 ERROR 42749 --- [           main] o.s.batch.core.step.AbstractStep         : Encountered an error executing step search-export in job searchExportJob

org.hibernate.LazyInitializationException: failed to lazily initialize a collection of role: com.example.hibernatenlp.ProductEntity.name, could not initialize proxy - no Session
	at org.hibernate.collection.internal.AbstractPersistentCollection.throwLazyInitializationException(AbstractPersistentCollection.java:606) ~[hibernate-core-5.4.27.Final.jar:5.4.27.Final]
	at org.hibernate.collection.internal.AbstractPersistentCollection.withTemporarySessionIfNeeded(AbstractPersistentCollection.java:218) ~[hibernate-core-5.4.27.Final.jar:5.4.27.Final]
	at org.hibernate.collection.internal.AbstractPersistentCollection.readElementByIndex(AbstractPersistentCollection.java:382) ~[hibernate-core-5.4.27.Final.jar:5.4.27.Final]
	at org.hibernate.collection.internal.PersistentMap.get(PersistentMap.java:172) ~[hibernate-core-5.4.27.Final.jar:5.4.27.Final]
	at com.example.hibernatenlp.ProductEntity.getLocalizedValue(ProductEntity.java:102) ~[classes/:na]
	at com.example.hibernatenlp.ProductEntity.getName(ProductEntity.java:77) ~[classes/:na]
	at com.example.hibernatenlp.HibernateNlpApplication.lambda$defaultItemProcessor$0(HibernateNlpApplication.java:131) ~[classes/:na]
	at jdk.internal.reflect.GeneratedMethodAccessor45.invoke(Unknown Source) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:344) ~[spring-aop-5.3.3.jar:5.3.3]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:198) ~[spring-aop-5.3.3.jar:5.3.3]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[spring-aop-5.3.3.jar:5.3.3]
	at org.springframework.aop.support.DelegatingIntroductionInterceptor.doProceed(DelegatingIntroductionInterceptor.java:137) ~[spring-aop-5.3.3.jar:5.3.3]
	at org.springframework.aop.support.DelegatingIntroductionInterceptor.invoke(DelegatingIntroductionInterceptor.java:124) ~[spring-aop-5.3.3.jar:5.3.3]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.3.3.jar:5.3.3]
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:215) ~[spring-aop-5.3.3.jar:5.3.3]
	at com.sun.proxy.$Proxy81.process(Unknown Source) ~[na:na]
	at org.springframework.batch.core.step.item.SimpleChunkProcessor.doProcess(SimpleChunkProcessor.java:134) ~[spring-batch-core-4.3.1.jar:4.3.1]
	at org.springframework.batch.core.step.item.SimpleChunkProcessor.transform(SimpleChunkProcessor.java:319) ~[spring-batch-core-4.3.1.jar:4.3.1]
	at org.springframework.batch.core.step.item.SimpleChunkProcessor.process(SimpleChunkProcessor.java:210) ~[spring-batch-core-4.3.1.jar:4.3.1]
	at org.springframework.batch.core.step.item.ChunkOrientedTasklet.execute(ChunkOrientedTasklet.java:77) ~[spring-batch-core-4.3.1.jar:4.3.1]
	at org.springframework.batch.core.step.tasklet.TaskletStep$ChunkTransactionCallback.doInTransaction(TaskletStep.java:407) ~[spring-batch-core-4.3.1.jar:4.3.1]
	at org.springframework.batch.core.step.tasklet.TaskletStep$ChunkTransactionCallback.doInTransaction(TaskletStep.java:331) ~[spring-batch-core-4.3.1.jar:4.3.1]
	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:140) ~[spring-tx-5.3.3.jar:5.3.3]
	at org.springframework.batch.core.step.tasklet.TaskletStep$2.doInChunkContext(TaskletStep.java:273) ~[spring-batch-core-4.3.1.jar:4.3.1]
	at org.springframework.batch.core.scope.context.StepContextRepeatCallback.doInIteration(StepContextRepeatCallback.java:82) ~[spring-batch-core-4.3.1.jar:4.3.1]
	at org.springframework.batch.repeat.support.TaskExecutorRepeatTemplate$ExecutingRunnable.run(TaskExecutorRepeatTemplate.java:262) ~[spring-batch-infrastructure-4.3.1.jar:4.3.1]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]

2021-02-02 10:19:24.327  INFO 42749 --- [           main] o.s.batch.core.step.AbstractStep         : Step: [search-export] executed in 2s487ms
2021-02-02 10:19:24.330  INFO 42749 --- [           main] o.s.b.c.l.support.SimpleJobLauncher      : Job: [SimpleJob: [name=searchExportJob]] completed with the following parameters: [{run.id=1}] and the following status: [FAILED] in 2s517ms
2021-02-02 10:19:24.334  INFO 42749 --- [extShutdownHook] o.s.s.concurrent.ThreadPoolTaskExecutor  : Shutting down ExecutorService 'defaultSearchExportTaskExecutor'
2021-02-02 10:19:24.334  INFO 42749 --- [extShutdownHook] j.LocalContainerEntityManagerFactoryBean : Closing JPA EntityManagerFactory for persistence unit 'default'
2021-02-02 10:19:24.334  INFO 42749 --- [extShutdownHook] .SchemaDropperImpl$DelayedDropActionImpl : HHH000477: Starting delayed evictData of schema as part of SessionFactory shut-down'
2021-02-02 10:19:24.340  INFO 42749 --- [extShutdownHook] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown initiated...
2021-02-02 10:19:24.343  INFO 42749 --- [extShutdownHook] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown completed.
```

and also:

```
2021-02-02 10:20:40.477 ERROR 42763 --- [search-export-4] ication$$EnhancerBySpringCGLIB$$b1a200b0 : processing product: 2827 with name: Sonair
2021-02-02 10:20:40.481 ERROR 42763 --- [           main] o.s.batch.core.step.AbstractStep         : Encountered an error executing step search-export in job searchExportJob

java.lang.NullPointerException: null
	at org.hibernate.collection.internal.PersistentMap.get(PersistentMap.java:174) ~[hibernate-core-5.4.27.Final.jar:5.4.27.Final]
	at com.example.hibernatenlp.ProductEntity.getLocalizedValue(ProductEntity.java:102) ~[classes/:na]
	at com.example.hibernatenlp.ProductEntity.getName(ProductEntity.java:77) ~[classes/:na]
	at com.example.hibernatenlp.HibernateNlpApplication.lambda$defaultItemProcessor$0(HibernateNlpApplication.java:131) ~[classes/:na]
	at jdk.internal.reflect.GeneratedMethodAccessor45.invoke(Unknown Source) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:344) ~[spring-aop-5.3.3.jar:5.3.3]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:198) ~[spring-aop-5.3.3.jar:5.3.3]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[spring-aop-5.3.3.jar:5.3.3]
	at org.springframework.aop.support.DelegatingIntroductionInterceptor.doProceed(DelegatingIntroductionInterceptor.java:137) ~[spring-aop-5.3.3.jar:5.3.3]
	at org.springframework.aop.support.DelegatingIntroductionInterceptor.invoke(DelegatingIntroductionInterceptor.java:124) ~[spring-aop-5.3.3.jar:5.3.3]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.3.3.jar:5.3.3]
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:215) ~[spring-aop-5.3.3.jar:5.3.3]
	at com.sun.proxy.$Proxy80.process(Unknown Source) ~[na:na]
	at org.springframework.batch.core.step.item.SimpleChunkProcessor.doProcess(SimpleChunkProcessor.java:134) ~[spring-batch-core-4.3.1.jar:4.3.1]
	at org.springframework.batch.core.step.item.SimpleChunkProcessor.transform(SimpleChunkProcessor.java:319) ~[spring-batch-core-4.3.1.jar:4.3.1]
	at org.springframework.batch.core.step.item.SimpleChunkProcessor.process(SimpleChunkProcessor.java:210) ~[spring-batch-core-4.3.1.jar:4.3.1]
	at org.springframework.batch.core.step.item.ChunkOrientedTasklet.execute(ChunkOrientedTasklet.java:77) ~[spring-batch-core-4.3.1.jar:4.3.1]
	at org.springframework.batch.core.step.tasklet.TaskletStep$ChunkTransactionCallback.doInTransaction(TaskletStep.java:407) ~[spring-batch-core-4.3.1.jar:4.3.1]
	at org.springframework.batch.core.step.tasklet.TaskletStep$ChunkTransactionCallback.doInTransaction(TaskletStep.java:331) ~[spring-batch-core-4.3.1.jar:4.3.1]
	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:140) ~[spring-tx-5.3.3.jar:5.3.3]
	at org.springframework.batch.core.step.tasklet.TaskletStep$2.doInChunkContext(TaskletStep.java:273) ~[spring-batch-core-4.3.1.jar:4.3.1]
	at org.springframework.batch.core.scope.context.StepContextRepeatCallback.doInIteration(StepContextRepeatCallback.java:82) ~[spring-batch-core-4.3.1.jar:4.3.1]
	at org.springframework.batch.repeat.support.TaskExecutorRepeatTemplate$ExecutingRunnable.run(TaskExecutorRepeatTemplate.java:262) ~[spring-batch-infrastructure-4.3.1.jar:4.3.1]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]
```

Both of them seem to be related to the fact that collections in your domain object `ProductEntity` are [lazily initialized](https://github.com/ptahchiev/hibernate-nlp/blob/master/src/main/java/com/example/hibernatenlp/ProductEntity.java#L32-L48). Changing the fetch type to `EAGER` in both of them fixes the issue.

Now the question is: why this lazy initialization works in a single-threaded scenario and not in a multi-threaded scenario? This seems to be related to how proxies are created by the `RepostioryItemReader` (which is backed by a Spring Data repository), because the same sample (lazy initialized collections and multi-threaded step) works fine by using the following `HibernatePagingItemReader`:

```java
@Bean
public HibernatePagingItemReader<ProductEntity> productReader(EntityManagerFactory entityManagerFactory) {
    return new HibernatePagingItemReaderBuilder<ProductEntity>()
            .name("itemReader")
            .sessionFactory(entityManagerFactory.unwrap(SessionFactory.class))
            .saveState(false)
            .queryString("from product")
            .build();
}
```

Do you confirm?

**Comment by ptahchiev** [comment]
Hi @benas I tried replacing my productReader with your productReader but I still get:

```
2021-02-02 13:45:10.598  INFO 49968 --- [           main] o.s.batch.core.job.SimpleStepHandler     : Executing step: [search-export]
2021-02-02 13:45:10.921 ERROR 49968 --- [           main] o.s.batch.core.step.AbstractStep         : Encountered an error executing step search-export in job searchExportJob

org.hibernate.LazyInitializationException: failed to lazily initialize a collection of role: com.example.hibernatenlp.ProductEntity.name, could not initialize proxy - no Session
	at org.hibernate.collection.internal.AbstractPersistentCollection.throwLazyInitializationException(AbstractPersistentCollection.java:606) ~[hibernate-core-5.4.27.Final.jar:5.4.27.Final]
	at org.hibernate.collection.internal.AbstractPersistentCollection.withTemporarySessionIfNeeded(AbstractPersistentCollection.java:218) ~[hibernate-core-5.4.27.Final.jar:5.4.27.Final]
	at org.hibernate.collection.internal.AbstractPersistentCollection.readElementByIndex(AbstractPersistentCollection.java:382) ~[hibernate-core-5.4.27.Final.jar:5.4.27.Final]
	at org.hibernate.collection.internal.PersistentMap.get(PersistentMap.java:172) ~[hibernate-core-5.4.27.Final.jar:5.4.27.Final]
	at com.example.hibernatenlp.ProductEntity.getLocalizedValue(ProductEntity.java:102) ~[classes/:na]
	at com.example.hibernatenlp.ProductEntity.getName(ProductEntity.java:77) ~[classes/:na]
	at com.example.hibernatenlp.HibernateNlpApplication.lambda$defaultItemProcessor$0(HibernateNlpApplication.java:124) ~[classes/:na]
```
I think there needs to be a `@Transactional` annotation somewhere. I tried adding it on the reader bean definition but it didn't help :(

**Comment by fmbenhassine** [comment]
my bad, I forgot to mention that I also added `spring.jpa.properties.hibernate.enable_lazy_load_no_trans=true` to the `application.properties` for that to work with the `HibernatePagingItemReader`. By the way, with that property, using the `JpaPagingItemReader` works as well:

```java
    @Bean
    public JpaPagingItemReader<ProductEntity> productReader(EntityManagerFactory entityManagerFactory) {
        return new JpaPagingItemReaderBuilder<ProductEntity>()
                .saveState(false)
                .queryString("from product")
                .entityManagerFactory(entityManagerFactory)
                .build();
    }
```

The `hibernate.enable_lazy_load_no_trans` property is controversial. Some folks consider it as an anti-pattern, but I think it is provided by hibernate for a good reason (it might be inappropriate to use in web apps with the open-session-in-view pattern, but it's probably ok to use in batch apps). So it is up to you to decide here. BTW, using that same property with the `RepositoryItemReader` gives the following exception in Hibernate's code:

```
2021-02-03 10:09:57.590  WARN 65077 --- [search-export-3] o.h.e.loading.internal.LoadContexts      : HHH000100: Fail-safe cleanup (collections) : org.hibernate.engine.loading.internal.CollectionLoadContext@303f413c<rs=HikariProxyResultSet@1818974215 wrapping rs108071: null>
2021-02-03 10:09:57.592 ERROR 65077 --- [           main] o.s.batch.core.step.AbstractStep         : Encountered an error executing step search-export in job searchExportJob

org.hibernate.AssertionFailure: bug adding collection twice
	at org.hibernate.engine.internal.StatefulPersistenceContext.addCollection(StatefulPersistenceContext.java:920) ~[hibernate-core-5.4.27.Final.jar:5.4.27.Final]
	at org.hibernate.engine.internal.StatefulPersistenceContext.addInitializedCollection(StatefulPersistenceContext.java:968) ~[hibernate-core-5.4.27.Final.jar:5.4.27.Final]
	at org.hibernate.engine.loading.internal.CollectionLoadContext.endLoadingCollection(CollectionLoadContext.java:247) ~[hibernate-core-5.4.27.Final.jar:5.4.27.Final]
	at org.hibernate.engine.loading.internal.CollectionLoadContext.endLoadingCollections(CollectionLoadContext.java:224) ~[hibernate-core-5.4.27.Final.jar:5.4.27.Final]
	at org.hibernate.engine.loading.internal.CollectionLoadContext.endLoadingCollections(CollectionLoadContext.java:198) ~[hibernate-core-5.4.27.Final.jar:5.4.27.Final]
	at org.hibernate.loader.plan.exec.process.internal.CollectionReferenceInitializerImpl.endLoading(CollectionReferenceInitializerImpl.java:154) ~[hibernate-core-5.4.27.Final.jar:5.4.27.Final]
	at org.hibernate.loader.plan.exec.process.internal.AbstractRowReader.finishLoadingCollections(AbstractRowReader.java:260) ~[hibernate-core-5.4.27.Final.jar:5.4.27.Final]
	at org.hibernate.loader.plan.exec.process.internal.AbstractRowReader.finishUp(AbstractRowReader.java:211) ~[hibernate-core-5.4.27.Final.jar:5.4.27.Final]
	at org.hibernate.loader.plan.exec.process.internal.ResultSetProcessorImpl.extractResults(ResultSetProcessorImpl.java:96) ~[hibernate-core-5.4.27.Final.jar:5.4.27.Final]
	at org.hibernate.loader.plan.exec.internal.AbstractLoadPlanBasedLoader.executeLoad(AbstractLoadPlanBasedLoader.java:105) ~[hibernate-core-5.4.27.Final.jar:5.4.27.Final]
	at org.hibernate.loader.collection.plan.AbstractLoadPlanBasedCollectionInitializer.initialize(AbstractLoadPlanBasedCollectionInitializer.java:87) ~[hibernate-core-5.4.27.Final.jar:5.4.27.Final]
	at org.hibernate.persister.collection.AbstractCollectionPersister.initialize(AbstractCollectionPersister.java:710) ~[hibernate-core-5.4.27.Final.jar:5.4.27.Final]
	at org.hibernate.event.internal.DefaultInitializeCollectionEventListener.onInitializeCollection(DefaultInitializeCollectionEventListener.java:76) ~[hibernate-core-5.4.27.Final.jar:5.4.27.Final]
	at org.hibernate.event.service.internal.EventListenerGroupImpl.fireEventOnEachListener(EventListenerGroupImpl.java:102) ~[hibernate-core-5.4.27.Final.jar:5.4.27.Final]
	at org.hibernate.internal.SessionImpl.initializeCollection(SessionImpl.java:2163) ~[hibernate-core-5.4.27.Final.jar:5.4.27.Final]
	at org.hibernate.collection.internal.AbstractPersistentCollection$4.doWork(AbstractPersistentCollection.java:589) ~[hibernate-core-5.4.27.Final.jar:5.4.27.Final]
	at org.hibernate.collection.internal.AbstractPersistentCollection.withTemporarySessionIfNeeded(AbstractPersistentCollection.java:264) ~[hibernate-core-5.4.27.Final.jar:5.4.27.Final]
	at org.hibernate.collection.internal.AbstractPersistentCollection.initialize(AbstractPersistentCollection.java:585) ~[hibernate-core-5.4.27.Final.jar:5.4.27.Final]
	at org.hibernate.collection.internal.AbstractPersistentCollection.read(AbstractPersistentCollection.java:149) ~[hibernate-core-5.4.27.Final.jar:5.4.27.Final]
	at org.hibernate.collection.internal.AbstractPersistentCollection$1ExtraLazyElementByIndexReader.doWork(AbstractPersistentCollection.java:374) ~[hibernate-core-5.4.27.Final.jar:5.4.27.Final]
	at org.hibernate.collection.internal.AbstractPersistentCollection.withTemporarySessionIfNeeded(AbstractPersistentCollection.java:264) ~[hibernate-core-5.4.27.Final.jar:5.4.27.Final]
	at org.hibernate.collection.internal.AbstractPersistentCollection.readElementByIndex(AbstractPersistentCollection.java:382) ~[hibernate-core-5.4.27.Final.jar:5.4.27.Final]
	at org.hibernate.collection.internal.PersistentMap.get(PersistentMap.java:172) ~[hibernate-core-5.4.27.Final.jar:5.4.27.Final]
	at com.example.hibernatenlp.ProductEntity.getLocalizedValue(ProductEntity.java:102) ~[classes/:na]
	at com.example.hibernatenlp.ProductEntity.getName(ProductEntity.java:77) ~[classes/:na]
	at com.example.hibernatenlp.HibernateNlpApplication.lambda$defaultItemProcessor$0(HibernateNlpApplication.java:164) ~[classes/:na]
	at jdk.internal.reflect.GeneratedMethodAccessor46.invoke(Unknown Source) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:344) ~[spring-aop-5.3.3.jar:5.3.3]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:198) ~[spring-aop-5.3.3.jar:5.3.3]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[spring-aop-5.3.3.jar:5.3.3]
	at org.springframework.aop.support.DelegatingIntroductionInterceptor.doProceed(DelegatingIntroductionInterceptor.java:137) ~[spring-aop-5.3.3.jar:5.3.3]
	at org.springframework.aop.support.DelegatingIntroductionInterceptor.invoke(DelegatingIntroductionInterceptor.java:124) ~[spring-aop-5.3.3.jar:5.3.3]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.3.3.jar:5.3.3]
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:215) ~[spring-aop-5.3.3.jar:5.3.3]
	at com.sun.proxy.$Proxy82.process(Unknown Source) ~[na:na]
	at org.springframework.batch.core.step.item.SimpleChunkProcessor.doProcess(SimpleChunkProcessor.java:134) ~[spring-batch-core-4.3.1.jar:4.3.1]
	at org.springframework.batch.core.step.item.SimpleChunkProcessor.transform(SimpleChunkProcessor.java:319) ~[spring-batch-core-4.3.1.jar:4.3.1]
	at org.springframework.batch.core.step.item.SimpleChunkProcessor.process(SimpleChunkProcessor.java:210) ~[spring-batch-core-4.3.1.jar:4.3.1]
	at org.springframework.batch.core.step.item.ChunkOrientedTasklet.execute(ChunkOrientedTasklet.java:77) ~[spring-batch-core-4.3.1.jar:4.3.1]
	at org.springframework.batch.core.step.tasklet.TaskletStep$ChunkTransactionCallback.doInTransaction(TaskletStep.java:407) ~[spring-batch-core-4.3.1.jar:4.3.1]
	at org.springframework.batch.core.step.tasklet.TaskletStep$ChunkTransactionCallback.doInTransaction(TaskletStep.java:331) ~[spring-batch-core-4.3.1.jar:4.3.1]
	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:140) ~[spring-tx-5.3.3.jar:5.3.3]
	at org.springframework.batch.core.step.tasklet.TaskletStep$2.doInChunkContext(TaskletStep.java:273) ~[spring-batch-core-4.3.1.jar:4.3.1]
	at org.springframework.batch.core.scope.context.StepContextRepeatCallback.doInIteration(StepContextRepeatCallback.java:82) ~[spring-batch-core-4.3.1.jar:4.3.1]
	at org.springframework.batch.repeat.support.TaskExecutorRepeatTemplate$ExecutingRunnable.run(TaskExecutorRepeatTemplate.java:262) ~[spring-batch-infrastructure-4.3.1.jar:4.3.1]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]
```

> I think there needs to be a @Transactional annotation somewhere. I tried adding it on the reader bean definition but it didn't help :(

Adding `@Transactional` on a method means execute that method in a transaction. Adding `@Transactional` on the item reader's bean definition method won't make the reader transactional, but will call this method in a transaction while configuring the application context. Obviously that won't help too much.

I don't think there is a need to add `@Transactional` somewhere, note how it works with `HibernatePaginItemReader` and `JpaPagngItemReader` without that annotation. I believe the problem is related to how the hibernate session is shared between threads (confirming that requires more digging to figure out the root cause), but at least I tried to help you getting a working solution. Another option would be making those collections eagerly loaded if that is an option for you.

**Comment by ptahchiev** [comment]
Hi @benas and thank you so much for your help, I really appreciate it. 

My problem is that I am building a web app and the batch runs in the background (it exports product from mysql to elasticsearch every 15 mins) and I cannot allow `hibernate.enable_lazy_load_no_trans`. Making the collections eagerly load is also not a real solution because it will make the rest of the website slow - every time I need a product from the db it will load the whole graph :(

What would be the correct way to implement here? Can you share some more ideas.

**Comment by fmbenhassine** [comment]
I see now and I understand your problem because I have been there as well..

> What would be the correct way to implement here? Can you share some more ideas.

Sure. Two lessons I learned the hard way after several years of identical/similar situations of time-wasting hair-pulling debugging sessions:

1. Do not use ORMs in batch applications. Straight JDBC is the way to go.
2. Do not run batch jobs in servlet containers.

I won't elaborate on that in too much details now (this could be subject of an entire blog post or talk), but the main reasons are: simplicity, performance and most importantly, the time saved by avoiding the debugging sessions of ORM proxies, lazy-loading exceptions, session/transaction management issues, etc. Note how much time you have wasted on this issue which was asked almost a month ago.. 

If it were up to me, I would write a batch job using a JDBC-based reader and a custom writer that uses elastic's [bulk request API](https://www.elastic.co/guide/en/elasticsearch/client/java-rest/master/java-rest-high-document-bulk.html). The job would be packaged in its own jar and scheduled independently. I guess items to index in elastic are independent from each others, so if a serial execution is slow, then a partitioned step is a good option to improve the performance.

**Comment by ptahchiev** [comment]
Hi @benas and thank you for your input. I guess i will have to try to use straight JDBC for the export. We already have the second part (item processor to convert to json, and item writer that uses the elasticsearch bulk API). My biggest concern is that `Product` is quite a heavy object with lots of relationships so this would be a very complicated JDBC query. 
I'll give it a try in the next few weeks and I will let you know :)
